"use client";

import type { Metadata } from "next";
import { Roboto} from "next/font/google";
import "./globals.css";

import { PomodoroProvider } from "./context/pomo-context";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight:['400','500','700'] ,subsets:["latin"]});
// const abel = Abel({weight:'400',subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} relative bg-primary h-screen flex flex-col justify-around items-center text-center text-light`}>
        <PomodoroProvider>{children}</PomodoroProvider>
      </body>
    </html>
  );
}
